[pyprland]
plugins = [ "scratchpads" ]

[scratchpads.term]
animation = ""
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
size = "75% 60%"
max_size = "1920px 100%"
margin = 50

[scratchpads.filemanager]
animation = ""
command = "kitty --class kitty-filemanager ranger"
class = "kitty-filemanager"
size = "50% 50%"
unfocus = "hide"
lazy = true

[scratchpads.music]
animation = ""
command = "kitty --class kitty-music rmpc"
class = "kitty-music"
size = "50% 50%"
unfocus = "hide"
lazy = true
